output "cluster_id" {
  description = "EKS cluster ID."
  value       = module.eks.cluster_id
}


output "lb-web-arn" {
  description = "ARN for WEB target group "
  value       = aws_lb_target_group.lb-web-tg.arn
}

output "lb-api-arn" {
  description = "ARN for API target group "
  value       = aws_lb_target_group.lb-api-tg.arn
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "redis_nodes" {
  description = "redis nodes list"
  value       = aws_elasticache_cluster.segmentme-redis.cache_nodes
}
output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "region" {
  description = "AWS region"
  value       = var.region
}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = local.cluster_name
}
