replicaCount: 1
limit:
  memory: 512Mi
  request: 512Mi
maxUnavailable: 30%
horizontalPodAutoScaler:
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
service:
  type: ClusterIP
env:
  SEGMENTME_DB_CONNECTOR_URI: $SEGMENTME_DB_CONNECTOR_URI
  AUTH0_CLIENT_ID: $AUTH0_CLIENT_ID
  AUTH0_CLIENT_SECRET: $AUTH0_CLIENT_SECRET
  SME_BE_HOST: $SME_BE_HOST
  ACCESS_SERVICE_HOST: $ACCESS_SERVICE_HOST
  ANALYSIS_SERVICE_HOST: $ANALYSIS_SERVICE_HOST
  MANAGEMENT_SERVICE_HOST: $MANAGEMENT_SERVICE_HOST
  MEASUREMENT_SERVICE_HOST: $MEASUREMENT_SERVICE_HOST
  CHANNEL_SERVICE_PORT: $CHANNEL_SERVICE_PORT
  CHANNEL_SERVICE_HOST: $CHANNEL_SERVICE_HOST
  REDIS_HOST: $REDIS_HOST
  REDIS_PORT: $REDIS_PORT