{{- define "common.service" -}}
{{- $common := dict "Values" .Values.common -}}
{{- $noCommon := omit .Values "common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}
{{- with merge $noValues $overrides $common -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.name" . }}
spec:
  selector:
    app: {{ include "common.name" . }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: {{ .Values.service.type }}
{{- end -}}
{{- end -}}