{{- define "common.authsecret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: auth0-secret
type: Opaque
data:
  AUTH0_CLIENT_ID: $AUTH0_CLIENT_ID_ENC
  AUTH0_CLIENT_SECRET: $AUTH0_CLIENT_SECRET_ENC
{{- end -}}