apiVersion: apps/v1
kind: Deployment
metadata:
    name: access-control-service
spec:
    selector:
        matchLabels:
            app: access-control-service
    replicas: 1
    template:
        metadata:
            labels:
                app: access-control-service
        spec:
            containers:
                -   name: access-control-service
                    image: $DOCKER_REGISTRY/segmentme-access-control-service
                    imagePullPolicy: Always
                    resources:
                        limits:
                            memory: 200Mi
                        requests:
                            memory: 150Mi
                    ports:
                        -   containerPort: 80
                    livenessProbe:
                        httpGet:
                            path: /actuator/health
                            port: 80
                        initialDelaySeconds: 200
                        timeoutSeconds: 5
                        periodSeconds: 20
                    env:
                        -   name: SEGMENTME_DB_CONNECTOR_URI
                            value: $SEGMENTME_DB_CONNECTOR_URI
                        -   name: AUTH0_CLIENT_ID
                            value: $AUTH0_CLIENT_ID
                        -   name: AUTH0_CLIENT_SECRET
                            value: $AUTH0_CLIENT_SECRET
                        -   name: SPRING_PROFILES_ACTIVE
                            value: "cloud"
---
apiVersion: v1
kind: Service
metadata:
    name: access-control-service
spec:
    selector:
        app: access-control-service
    ports:
        -   name: http
            protocol: TCP
            port: 80
            targetPort: 80
    type: ClusterIP

---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
    name: access-control-service
spec:
    selector:
        matchLabels:
            app: access-control-service
    maxUnavailable: 30%

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: access-control-service
spec:
    scaleTargetRef:
        apiVersion: extensions/v1beta1
        kind: Deployment
        name: access-control-service
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
                        
                        