apiVersion: apps/v1
kind: Deployment
metadata:
    name: access-control-service
spec:
    selector:
        matchLabels:
            app: access-control-service
    replicas: 1
    template:
        metadata:
            labels:
                app: access-control-service
        spec:
            containers:
                - name: access-control-service
                  image: ACS_IMAGE_NAME
                  imagePullPolicy: Always
                  resources:
                      limits:
                          cpu:  650m
                          memory: 650Mi
                      requests:
                          cpu: 500m
                          memory: 500Mi
                  ports:
                      - containerPort: 80
                  livenessProbe:
                      httpGet:
                          path: /access-control-service/actuator/health
                          port: 80
                      initialDelaySeconds: 200
                      timeoutSeconds: 5
                      periodSeconds: 20
                  env:
                      - name: SEGMENTME_DB_CONNECTOR_URI
                        value: "FIND_A_SECURED_WAY_FOR_INJECT_THIS_PROBABLY_WITH_KUBERNETES_SECRETS"
                      - name: AUTH0_CLIENT_ID
                        value: "FIND_A_SECURED_WAY_FOR_INJECT_THIS_PROBABLY_WITH_KUBERNETES_SECRETS"
                      - name: AUTH0_CLIENT_SECRET
                        value: "FIND_A_SECURED_WAY_FOR_INJECT_THIS_PROBABLY_WITH_KUBERNETES_SECRETS"
                      - name: SPRING_PROFILES_ACTIVE
                        value: "cloud"
---
apiVersion: v1
kind: Service
metadata:
    name: access-control-service
spec:
    selector:
        app: access-control-service
    ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 8080
    type: ClusterIP

---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
    name: access-control-service
spec:
    selector:
        matchLabels:
            app: access-control-service
    maxUnavailable: 30%

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: access-control-service
spec:
    scaleTargetRef:
        apiVersion: extensions/v1beta1
        kind: Deployment
        name: access-control-service
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
                        
                        