{{ define "common.evironment" -}}
            - name: SEGMENTME_DB_CONNECTOR_URI
              value: {{ .Values.env.SEGMENTME_DB_CONNECTOR_URI }}
            - name: REDIS_HOST
              value: {{ .Values.env.REDIS_HOST }}
            - name: REDIS_PORT
              value: {{ .Values.env.REDIS_PORT }}
            - name: REDIS_CONNECTION_TIMEOUT
              value: '25'
            - name: REDIS_READ_TIMEOUT
              value: '15'
            - name: AUTH0_CLIENT_ID
              value: {{ .Values.env.AUTH0_CLIENT_ID }}
            - name: AUTH0_CLIENT_SECRET
              value: {{ .Values.env.AUTH0_CLIENT_SECRET }}
            - name: ACCESS_SERVICE_HOST
              value: {{ .Values.env.ACCESS_SERVICE_HOST }}
            - name: MEASUREMENT_SERVICE_HOST
              value: {{ .Values.env.MEASUREMENT_SERVICE_HOST }}
            - name: ANALYSIS_CORE_POOL_SIZE
              value: '10'
            - name: ANALYSIS_MAX_POOL_SIZE
              value: '10'
            - name: ANALYSIS_QUEUE_POOL_SIZE
              value: '50'
            - name: ANALYSIS_THREAD_NAME_PREFIX
              value: "analysis-executor-"
            - name: ASYNC_CORE_POOL_SIZE
              value: '10'
            - name: ASYNC_MAX_POOL_SIZE
              value: '10'
            - name: ASYNC_QUEUE_POOL_SIZE
              value: '50'
            - name: ASYNC_THREAD_NAME_PREFIX
              value: "async-executor-"
{{- end -}}